services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 3002:8081
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  redis-commander:
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 3003:8081

volumes:
  mongo:
  redis:
