@startuml Web App Authentication Flow

actor User
participant "Web App" as WebApp
participant API
participant Strava

User -> WebApp: Click Login
WebApp -> API: Redirect to GET /auth/login
API -> Strava: Redirect to OAuth authorize
note right
  GET https://www.strava.com/oauth/authorize
  client_id
  redirect_uri = "/auth/callback"
  response_type = "code"
  scope = "activity:read_all"
end note
Strava --> User: Show authorization screen

User -> Strava: Approve authorization
Strava --> API: Redirect to GET /auth/callback\n(with code, scope, state)

API -> Strava: Exchange code
note right
  POST https://www.strava.com/api/v3/oauth/token
  client_id
  client_secret
  code
  grant_type = "authorization_code"
end note
Strava --> API: Return access_token, refresh_token,\nexpires_at, athlete ID

API -> API: Create/update user based on athlete ID,\nsave Strava tokens to database
API -> API: Create Web access and refresh tokens
API -> API: Attach tokens as HTTP only cookies to response
API --> WebApp: Redirect to Web App

WebApp -> API: GET /auth/me
API --> WebApp: Confirm authenticated state

WebApp -> User: Show authenticated state

@enduml
